Fixes user rights in log folder and introduces a common jitsi group.

diff --git a/resources/install/debian/postinst b/resources/install/debian/postinst
--- a/resources/install/debian/postinst
+++ b/resources/install/debian/postinst
@@ -8,7 +8,7 @@ case "$1" in
 
         CONFIG="/etc/jitsi/jicofo/config"
 
-	    # we don't want to regenerate config on upgrade
+        # we don't want to regenerate config on upgrade
         OLDCONFIG="false"
         if [ -f $CONFIG ]; then
             . $CONFIG
@@ -31,7 +31,7 @@ case "$1" in
             JICOFO_AUTH_DOMAIN="auth.$JICOFO_HOSTNAME"
             JICOFO_AUTH_USER="focus"
             JICOFO_AUTH_PASSWORD=`head -c 8 /dev/urandom | tr '\0-\377' 'a-zA-Z0-9a-zA-Z0-9a-zA-Z0-9a-zA-Z0-9@@@@####'`
-            
+
             # storing default
             echo '# Jitsi Conference Focus settings' > $CONFIG
             echo "JICOFO_HOST=localhost" >> $CONFIG
@@ -46,8 +46,14 @@ case "$1" in
         fi
 
         # we don't want to start the daemon as root
+        if ! getent group jitsi > /dev/null ; then
+            groupadd jitsi
+        fi
         if ! getent passwd jicofo > /dev/null ; then
-            useradd -r --user-group --shell /bin/bash --create-home -d /usr/share/jicofo jicofo
+            useradd -r -g jitsi --shell /bin/bash --create-home -d /usr/share/jicofo jicofo
+        fi
+        if ! groups jicofo | grep '\bjitsi\b' > /dev/null ; then
+            usermod -g jitsi jicofo
         fi
 
         # we create home folder only if it doesn't exist
@@ -58,18 +64,24 @@ case "$1" in
         # we claim the home folder of jicofo in case it is owned by someone else
         OWNER=$(stat -c '%U' /usr/share/jicofo)
         GROUP=$(stat -c '%G' /usr/share/jicofo)
-        if ! dpkg-statoverride --list /usr/share/jicofo/* >/dev/null && [ "$OWNER:$GROUP" != "jicofo:jicofo" ]; then
-            chown -R jicofo:jicofo /usr/share/jicofo
+        if ! dpkg-statoverride --list /usr/share/jicofo/* >/dev/null && [ "$OWNER:$GROUP" != "jicofo:jitsi" ]; then
+            chown -R jicofo:jitsi /usr/share/jicofo
             OWNER=jicofo
-            GROUP=jicofo
+            GROUP=jitsi
         fi
 
         # die logz
-        chmod o+w /var/log/jitsi/
+        chown -R $OWNER:$GROUP /var/log/jitsi/jicofo*
+        chmod -R 640 /var/log/jitsi/jicofo*
 
         # ensure focus is not running - it will be started at the end
         if [ "$(pidof java)" ]; then
             invoke-rc.d jicofo stop || true
+        fi
+
+        # clean up old jicofo group
+        if getent group jicofo > /dev/null; then
+            groupdel jicofo
         fi
     ;;
 
